variables:
  PIPELINE_DOCKER_IMAGE: "adoptopenjdk/openjdk8"

image: $PIPELINE_DOCKER_IMAGE

before_script:
  - echo "$TASK_ARGUMENTS"

build:
  stage: build
  script:
    - ./gradlew build -x test $TASK_ARGUMENTS

test:
  stage: test
  script:
    - ./gradlew test $TASK_ARGUMENTS
  artifacts:
    when: always
    reports:
      junit: ./**/build/test-results/test/**/TEST-*.xml

deploy:
  stage: deploy
  before_script:
    - chmod +x gradlew
    - curl -o $CERT_INT_AD $CERT_ADDR/$CERT_INT_AD
    - curl -o $CERT_ROOT $CERT_ADDR/$CERT_ROOT
    - CERTS_PATH="jre/lib/security/cacerts"
    - keytool -keystore $JAVA_HOME/$CERTS_PATH -trustcacerts -importcert -alias cti-root -file ./$CERT_ROOT -storepass $ROOT_PASS -noprompt
    - keytool -keystore $JAVA_HOME/$CERTS_PATH -trustcacerts -importcert -alias cti-ad-ca -file ./$CERT_INT_AD -storepass $STORE_PASS -noprompt

  script:
    - ./gradlew build publish $TASK_ARGUMENTS
#  only:
#    - develop
